import PDFDocument from 'pdfkit';
import { ValidationResult } from '@/types';

export async function generatePDF(validationResult: ValidationResult, invoiceNumber: string): Promise<Buffer> {
    return new Promise((resolve, reject) => {
        const doc = new PDFDocument({ margin: 50 });
        const buffers: Buffer[] = [];

        doc.on('data', buffers.push.bind(buffers));
        doc.on('end', () => {
            const pdfData = Buffer.concat(buffers);
            resolve(pdfData);
        });

        // ─── Header ───────────────────────────────────────────────────────── (No Logo)
        doc.fontSize(20).text('GST Invoice Validation Report', { align: 'center' });
        doc.moveDown();
        doc.fontSize(12).text(`Invoice Number: ${invoiceNumber}`, { align: 'left' });
        doc.text(`Date: ${new Date().toLocaleDateString()}`, { align: 'left' });
        doc.moveDown();

        // ─── Health Score ───────────────────────────────────────────────────
        doc.fontSize(14).text('Health Score', { underline: true });

        const scoreColor = validationResult.healthScore >= 80 ? 'green' :
            validationResult.healthScore >= 50 ? 'orange' : 'red';

        doc.fillColor(scoreColor).fontSize(20).text(`${validationResult.healthScore}/100`, { align: 'left' });
        doc.fillColor('black').fontSize(12).text(`Risk Level: ${validationResult.riskLevel.toUpperCase()}`);
        doc.moveDown();

        // ─── Issues Found ───────────────────────────────────────────────────
        if (validationResult.issuesFound.length > 0) {
            doc.fontSize(14).text('Issues Found', { underline: true });
            doc.moveDown(0.5);

            validationResult.issuesFound.forEach((issue, index) => {
                doc.fontSize(12).fillColor('red').text(`${index + 1}. ${issue.title} (${issue.severity.toUpperCase()})`);
                doc.fontSize(10).fillColor('black').text(`   Description: ${issue.description}`);
                if (issue.howToFix) {
                    doc.text(`   Fix: ${issue.howToFix}`, { oblique: true });
                }
                doc.moveDown(0.5);
            });
        } else {
            doc.fontSize(14).fillColor('green').text('✅ No Issues Found - This invoice is compliant.');
        }

        doc.moveDown();

        // ─── Checks Passed ──────────────────────────────────────────────────
        if (validationResult.checksPassed.length > 0) {
            doc.fontSize(14).fillColor('black').text('Checks Passed', { underline: true });
            doc.moveDown(0.5);

            validationResult.checksPassed.forEach((check) => {
                doc.fontSize(10).text(`• ${check.title}`);
            });
        }

        doc.moveDown(2);

        // ─── Disclaimer ─────────────────────────────────────────────────────
        doc.fontSize(8).fillColor('grey').text(
            'DISCLAIMER: This report is generated by an automated system based on current GST laws. It simulates a tax audit but does not constitute legal or tax advice. Please consult a CA for critical matters.',
            { align: 'center' }
        );

        doc.end();
    });
}
